Making example work
`existing_terms()` expects a index reader as first parameter. I had to make this correction for the example to work.
```
<ipython-input-239-78fab482863d> in match(idx, query_str, limit)
     74 
     75         termset = set()
---> 76         query.existing_terms(termset)
     77 
     78         # query_bet = Or([Term('bestbet', text) for text in query.split(' ')])

/usr/local/lib/python3.7/site-packages/whoosh/query/qcore.py in existing_terms(self, ixreader, phrases, expand, fieldname)
    347         """
    348 
--> 349         schema = ixreader.schema
    350         termset = set()
    351 

AttributeError: 'set' object has no attribute 'schema'
```